# Generated by Django 2.1 on 2018-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Enter author name', max_length=32)),
                ('subject', models.CharField(help_text='Enter blog subject', max_length=256)),
                ('body', models.TextField(help_text='Enter blog body')),
            ],
        ),
    ]
